spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sub_verge
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yml
    enabled: true
